---
title: "Help Us in the Fight Against Misinformation"
subtitle: "An Open Letter to the Senior Administration @ the University of Guelph"
date: "09/07/2021"
bibliography: refs.bib
csl: american-medical-association.csl
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Sign the Letter Here](https://uoguelph.eu.qualtrics.com/jfe/form/SV_5ig6pPdprXSQjxs)

Since the beginning of the COVID-19 pandemic, scientists have taken an increasingly prominent role in the average Canadian’s day-to-day life. As we each look to make decisions to best protect ourselves, our loved ones, and our communities, we turn to experts in our healthcare and public health systems – and at our universities – to guide us by providing their interpretation of the best available scientific evidence.

Our job as public health researchers and students is to sift through this evidence, to use our knowledge and experience to evaluate its quality, and to distill our findings into recommendations for Canadians. As scientists, we regularly engage in intense debates over these ideas – debates that are a cornerstone of scientific discovery. Sometimes, we have strong disagreements. Nonetheless, we engage passionately in these debates, knowing this process is protected by the University of Guelph’s freedom of expression policy, which safeguards “the ability to examine, question, critique, investigate, inquire, speculate and communicate on issues without deference to prescribed doctrine”.

The privilege of academic freedom comes with important responsibilities. In the era of social media, we must recognize that these scientific debates are taking place in the public eye. We therefore have a responsibility to provide the public with sufficient context for our claims, such that the public understands the quality of the evidence we provide, and the agreement of our claims with scientific consensus.  Lack of this context leads to confusion, credentialism, and combativeness; not clarity, consensus, nor collaboration.

Recently, we have become aware of alarmist claims related to the COVID-19 vaccine made by Dr. Byram Bridle, an immunologist at the Ontario Veterinary College at University of Guelph. In brief, he asserts the spike proteins produced by the vaccine are cytotoxic, implying COVID-19 vaccines are harmful. While we believe it is fully within his right to make these claims, we also believe these claims are strongly misleading, and were presented in an irresponsible manner. Given their rapid amplification on social media, these claims have now necessitated 10 separate fact-checks – all of which have concluded that the claims were either false or misleading. Moreover, one of the authors of the papers cited as a basis for these claims has rebutted these statements. Such blatant misinformation confuses the public, who have the right to make informed decisions, and undermines public trust in life-saving vaccines amidst a public health crisis. We have included references to these works and additional resources in the appendix to this letter.

To their credit, the University of Guelph has released a generic statement on their website reaffirming its unequivocal support of vaccination. However, this is simply not enough, and is not in the appropriate form to combat misinformation online and in social media.  When misinformation spreads on social media platforms – bolstered by the credibility and prestige of the University – it should be specifically addressed by the University. The lack of response leads to the public’s assumption that these claims are supported by the University of Guelph and may lead members of the public to make decisions that may negatively impact personal and public health. As students, especially in a public health program, we’re frustrated with how this reflects on the University of Guelph.

Moreover, in the absence of a sufficient response, it has fallen to individual scientists at the University of Guelph to spend a disproportionate amount of their own time (see [Brandolini's law](https://en.wikipedia.org/wiki/Brandolini%27s_law)) fighting misinformation arising from these claims. As a result, these fact-checkers have faced public accusations of harassment, threats of lawsuits, and have become targets of online hate – fueled by claims of censorship on national television (which further erodes public trust in our scientific institutions and processes).

The University of Guelph can, should, and must do more to combat misinformation. Especially when that misinformation originates locally, and especially when they have given the author a platform to make similar claims in the past. To that end, we ask that the University of Guelph:

-	Elevate the voices of fact-checkers by providing them a platform and promoting their works via the University’s social media accounts (e.g. in the University’s news and publications).
-	Establish policies to protect fact-checkers against spurious legal claims (including accusations of engaging in harassment) and demonstrate a clear willingness to stand by these policies or protections in the future.
-	Commit to amplifying the University’s position on matters relevant to public health via the University’s social media accounts.

Our motto at the U of G is to Improve Life. The University should be embracing and utilizing the resources they have available – their researchers and students – to fight misinformation and further improve the lives of Canadians during the pandemic. We should not simply tolerate misinformation that impedes progress in ending this pandemic.

As of today, 27% of Canadians are fully vaccinated, and 67% of Canadians are partially vaccinated against COVID-19 with safe and effective vaccines – this is an incredible privilege.

Signed, 

-	Brennan Chapman
-	Amar Laila
- Sarah Hill
-	Wendy Xie
-	Catherine Belanger 

See more signatories below.

</br>
</br>

# Appendix

***



## {.tabset}

### Previous U of G Platforms

- OVC News (2020-06-17) [Fast COVID-19 vaccine timelines are unrealistic and put the integrity of scientists at risk](https://ovc.uoguelph.ca/news/fast-covid-19-vaccine-timelines-are-unrealistic-and-put-integrity-scientists-risk).
- UofG News (2020-11-19) [U of G Immunologist Has Concerns Over COVID-19 Vaccine Candidates](https://news.uoguelph.ca/2020/11/u-of-g-viral-immunologist-has-concerns-over-new-covid-19-vaccine-candidates/).
- UofG News (2021-03-12) [Immunologist Pens Commentary on Kids’ Health in COVID-19](https://news.uoguelph.ca/2021/03/immunologist-pens-commentary-on-kids-health-in-covid-19/).

### Claims

The main premise behind Dr. Bridle’s claims is that the spike proteins that are produced by cells from the mRNA sequence are cytotoxic. He also claims that the spike protein is distributed throughout the body and accumulates in organs. He claims that as a result of the cytotoxicity and distribution of the spike protein, the COVID-19 vaccines can cause damage to organs (including the brain and ovaries), leading to brain damage and infertility. In addition, he claims the spike protein may be transmitted through breastmilk and harm the infant.

These claims have already been debunked by several sources (see below), even by the authors of one of the papers he cites [@Manor2021]. To summarize these rebuttals:

- Some of the studies cited were misrepresented. For example, Lei et al. [-@Lei2021] show the SARS-CoV-2 virus’s spike protein alone can damage the endothelium, but the amount of spike protein produced from vaccination is many thousands of times lower [@Ogata2021].
- The spike protein encoded is modified to have a transmembrane protein, which keeps the spike proteins anchored to cells at the site of injection [@Lowe2021]. 
- Only 0.095% and 0.074% of the injected lipid nanoparticles (a marker for the vaccine – not the spike protein as claimed) appear in rat ovaries and testicles respectively [@PMDA2021].
- Several studies have shown no effect of COVID-19 vaccines on fertility or pregnancy outcomes [@Golan2021; @Mattar2021; @Morris2021; @Safrai2021; @Safrai2021a; @Shanes2021].
- Several studies have reported on the safety of these approved vaccines, including general vaccine recipients [@Mathioudakis2021; @Kataria2021], in recovered COVID-19 patients [@Arnold2021], and in phase 3 trials [@Baden2021; @Polack2020].
- To summarize, he ignores multiple studies showing the safety of these vaccines and misrepresents pharmacokinetic studies, adding to a false narrative that the currently approved COVID-19 vaccines are harmful.


### References

<div id="refs"></div>


### Fact-checks

- AFP Fact Check (2021-05-13) [Posts misrepresent US study on dangers of coronavirus spike protein](https://factcheck.afp.com/posts-misrepresent-us-study-dangers-coronavirus-spike-protein).
- USA Today (2021-06-08) [Fact check: COVID-19 vaccines don't produce dangerous toxins](https://www.usatoday.com/story/news/factcheck/2021/06/08/fact-check-proteins-covid-19-vaccines-arent-dangerous-toxins/7505236002/).
- Health Feedback (2021-06-08) [Byram Bridle’s claim that COVID-19 vaccines are toxic fails to account for key differences between the spike protein produced during infection and vaccination, misrepresents studies](https://healthfeedback.org/claimreview/byram-bridles-claim-that-covid-19-vaccines-are-toxic-fails-to-account-for-key-differences-between-the-spike-protein-produced-during-infection-and-vaccination-misrepresents-studies/).
- AP News (2021-06-09) [Spike protein produced by vaccine not toxic](https://apnews.com/article/fact-checking-377989296609).
- Reuters (2021-06-15) [Fact Check -- No evidence spike proteins from COVID-19 vaccines are toxic](https://www.reuters.com/article/factcheck-vaccine-safe-idUSL2N2NX1J6).
- PolitiFact (2021-06-16) [No sign that the COVID-19 vaccines’ spike protein is toxic or ‘cytotoxic’](https://www.politifact.com/factchecks/2021/jun/16/youtube-videos/no-sign-covid-19-vaccines-spike-protein-toxic-or-c/).
- PolitiFact (2021-06-17) [No sign spike proteins from COVID-19 vaccines, including Novavax, are dangerous](https://www.politifact.com/factchecks/2021/jun/17/facebook-posts/no-sign-spike-proteins-covid-19-vaccines-including/).
- Full Fact (2021-06-17) [Claims that Covid vaccine spike proteins are harmful are unevidenced](https://fullfact.org/online/conservative-woman-vaccine-scientist-spike-protein/).
- AFP Factenckeck (in German) (2021-06-17) [Dieser Professor verbreitet falsche Informationen über die Folgen von Corona-Impfungen](https://faktencheck.afp.com/http%253A%252F%252Fdoc.afp.com%252F9CE6WH-1).

## {-}

</br>
</br>

# Signatures

***

[Sign the Letter Here](https://uoguelph.eu.qualtrics.com/jfe/form/SV_5ig6pPdprXSQjxs)

Signatures Will be added shortly.


